services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  backend:
    image: transcribe-backend:latest
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - API_DATABASE_URL
      - API_PREFIX
      - API_VERSION
      - API_TITLE
      - API_DESCRIPTION
      - API_FILE_STORAGE_DIR
      - API_SECRET_KEY
      - API_WORKER_CLIENT_DN

      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - OIDC_METADATA_URL
      - OIDC_SCOPE
      - OIDC_REFRESH_URI
      - OIDC_REDIRECT_URI
      - OIDC_FRONTEND_URI

  frontend:
    image: transcribe-ui:latest
    depends_on:
      - backend
    ports:
      - "8888:8888"
    environment:
      - API_URL
      - OIDC_APP_REFRESH_ROUTE
      - OIDC_APP_LOGIN_ROUTE
      - OIDC_APP_LOGOUT_ROUTE
